"""Post-offer drop-off prediction — extension proof-of-concept.

Direct response to mid-sem viva feedback: the reviewer noted that predicting
drop-off at the post-offer stage (candidate accepts offer but never joins, or
declines after acceptance) has higher business value than predicting mid-
application drop-off.

This module is a scoped extension proving the same framework — XGBoost +
isotonic calibration + SHAP + RAG rationale — generalises to the post-offer
stage of the funnel. The features differ; the pipeline is identical.

WHY this is a proof-of-concept and NOT a full production model:
- No public dataset exists for post-offer decline events. Labels are
  synthetic, generated by `simulation.py` with correlations grounded in
  published research on offer-decline drivers.
- A production deployment would require partnership with an ATS vendor
  (e.g. Jobvite) to obtain real offer-acceptance/decline telemetry.
- The contribution of this module is *framework generality* — demonstrating
  that the retrieval → prediction → SHAP → RAG pipeline is stage-agnostic.

Documented in: reports/final_report.md §"Extending to post-offer drop-off".
"""
